apiVersion: v1
kind: Service
metadata:
  name: webapp-colorfont-svc
spec:
  type: NodePort
  selector:
    app: colorfont-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30008